"""
Export Router - CSV and Excel export functionality for data.
Provides export endpoints for equipment, tickets, contracts, and software.
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session, joinedload
from sqlalchemy import and_
from typing import Optional, List
from datetime import datetime, timezone
import csv
import io
import logging

from backend.core.database import get_db
from backend.core.security import get_current_user, get_current_admin_user
from backend import models, schemas

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/export", tags=["export"])


def generate_csv(data: List[dict], filename: str) -> StreamingResponse:
    """Generate a CSV file from a list of dictionaries."""
    if not data:
        output = io.StringIO()
        output.write("No data to export")
        output.seek(0)
        return StreamingResponse(
            iter([output.getvalue()]),
            media_type="text/csv",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )

    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=data[0].keys())
    writer.writeheader()
    writer.writerows(data)
    output.seek(0)

    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )


# ==================== EQUIPMENT EXPORT ====================

@router.get("/equipment")
def export_equipment(
    status: Optional[str] = None,
    equipment_type_id: Optional[int] = None,
    location_id: Optional[int] = None,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_admin_user)
):
    """Export equipment list to CSV."""
    query = db.query(models.Equipment).options(
        joinedload(models.Equipment.equipment_type),
        joinedload(models.Equipment.model),
        joinedload(models.Equipment.location),
        joinedload(models.Equipment.supplier)
    )

    # Apply entity filter
    if current_user.entity_id:
        query = query.filter(models.Equipment.entity_id == current_user.entity_id)

    # Apply filters
    if status:
        query = query.filter(models.Equipment.status == status)
    if equipment_type_id:
        query = query.filter(models.Equipment.equipment_type_id == equipment_type_id)
    if location_id:
        query = query.filter(models.Equipment.location_id == location_id)

    equipment_list = query.order_by(models.Equipment.name).all()

    data = []
    for eq in equipment_list:
        data.append({
            "id": eq.id,
            "name": eq.name,
            "status": eq.status,
            "type": eq.equipment_type.name if eq.equipment_type else "",
            "model": eq.model.name if eq.model else "",
            "manufacturer": eq.model.manufacturer.name if eq.model and eq.model.manufacturer else "",
            "serial_number": eq.serial_number or "",
            "asset_tag": eq.asset_tag or "",
            "location": eq.location.name if eq.location else "",
            "supplier": eq.supplier.name if eq.supplier else "",
            "purchase_date": eq.purchase_date.isoformat() if eq.purchase_date else "",
            "warranty_expiry": eq.warranty_expiry.isoformat() if eq.warranty_expiry else "",
            "purchase_price": eq.purchase_price or "",
            "ip_address": eq.remote_ip or "",
            "rack_position": f"U{eq.position_u}" if eq.position_u else "",
            "notes": eq.notes or "",
            "created_at": eq.created_at.isoformat() if eq.created_at else ""
        })

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"equipment_export_{timestamp}.csv"

    logger.info(f"Equipment export generated by {current_user.username}: {len(data)} items")
    return generate_csv(data, filename)


# ==================== TICKETS EXPORT ====================

@router.get("/tickets")
def export_tickets(
    status: Optional[str] = None,
    priority: Optional[str] = None,
    ticket_type: Optional[str] = None,
    date_from: Optional[str] = None,
    date_to: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    """Export tickets to CSV."""
    query = db.query(models.Ticket).options(
        joinedload(models.Ticket.requester),
        joinedload(models.Ticket.assigned_to),
        joinedload(models.Ticket.equipment)
    )

    # Access control
    if current_user.role != "admin":
        query = query.filter(models.Ticket.requester_id == current_user.id)
    elif current_user.entity_id:
        query = query.filter(models.Ticket.entity_id == current_user.entity_id)

    # Apply filters
    if status:
        query = query.filter(models.Ticket.status == status)
    if priority:
        query = query.filter(models.Ticket.priority == priority)
    if ticket_type:
        query = query.filter(models.Ticket.ticket_type == ticket_type)
    if date_from:
        try:
            from_date = datetime.fromisoformat(date_from)
            query = query.filter(models.Ticket.created_at >= from_date)
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid date_from format. Use ISO format.")
    if date_to:
        try:
            to_date = datetime.fromisoformat(date_to)
            query = query.filter(models.Ticket.created_at <= to_date)
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid date_to format. Use ISO format.")

    tickets = query.order_by(models.Ticket.created_at.desc()).all()

    data = []
    for t in tickets:
        data.append({
            "ticket_number": t.ticket_number,
            "title": t.title,
            "description": t.description or "",
            "type": t.ticket_type,
            "category": t.category or "",
            "status": t.status,
            "priority": t.priority,
            "requester": t.requester.username if t.requester else "",
            "assigned_to": t.assigned_to.username if t.assigned_to else "",
            "equipment": t.equipment.name if t.equipment else "",
            "sla_due_date": t.sla_due_date.isoformat() if t.sla_due_date else "",
            "sla_breached": "Yes" if t.sla_breached else "No",
            "resolution": t.resolution or "",
            "created_at": t.created_at.isoformat() if t.created_at else "",
            "resolved_at": t.resolved_at.isoformat() if t.resolved_at else "",
            "closed_at": t.closed_at.isoformat() if t.closed_at else ""
        })

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"tickets_export_{timestamp}.csv"

    logger.info(f"Tickets export generated by {current_user.username}: {len(data)} items")
    return generate_csv(data, filename)


# ==================== CONTRACTS EXPORT ====================

@router.get("/contracts")
def export_contracts(
    contract_type: Optional[str] = None,
    status: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_admin_user)
):
    """Export contracts to CSV."""
    query = db.query(models.Contract).options(
        joinedload(models.Contract.supplier)
    )

    # Apply entity filter
    if current_user.entity_id:
        query = query.filter(models.Contract.entity_id == current_user.entity_id)

    # Apply filters
    if contract_type:
        query = query.filter(models.Contract.contract_type == contract_type)
    if status:
        query = query.filter(models.Contract.status == status)

    contracts = query.order_by(models.Contract.end_date.desc()).all()

    data = []
    for c in contracts:
        data.append({
            "id": c.id,
            "name": c.name,
            "contract_number": c.contract_number or "",
            "type": c.contract_type,
            "status": c.status,
            "supplier": c.supplier.name if c.supplier else "",
            "start_date": c.start_date.isoformat() if c.start_date else "",
            "end_date": c.end_date.isoformat() if c.end_date else "",
            "annual_cost": c.annual_cost or "",
            "auto_renewal": "Yes" if c.auto_renewal else "No",
            "notice_period_days": c.notice_period_days or "",
            "support_level": c.support_level or "",
            "notes": c.notes or "",
            "created_at": c.created_at.isoformat() if c.created_at else ""
        })

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"contracts_export_{timestamp}.csv"

    logger.info(f"Contracts export generated by {current_user.username}: {len(data)} items")
    return generate_csv(data, filename)


# ==================== SOFTWARE EXPORT ====================

@router.get("/software")
def export_software(
    category: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_admin_user)
):
    """Export software catalog with license information to CSV."""
    query = db.query(models.Software)

    # Apply entity filter
    if current_user.entity_id:
        query = query.filter(models.Software.entity_id == current_user.entity_id)

    # Apply filters
    if category:
        query = query.filter(models.Software.category == category)

    software_list = query.order_by(models.Software.name).all()

    data = []
    for s in software_list:
        # Count licenses and installations
        license_count = len(s.licenses) if s.licenses else 0
        total_seats = sum(l.quantity for l in s.licenses) if s.licenses else 0
        installation_count = len(s.installations) if s.installations else 0

        data.append({
            "id": s.id,
            "name": s.name,
            "version": s.version or "",
            "publisher": s.publisher or "",
            "category": s.category or "",
            "license_type": s.license_type or "",
            "total_licenses": license_count,
            "total_seats": total_seats,
            "installations": installation_count,
            "compliance": "OK" if installation_count <= total_seats else "Over-deployed",
            "website": s.website or "",
            "notes": s.notes or "",
            "created_at": s.created_at.isoformat() if s.created_at else ""
        })

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"software_export_{timestamp}.csv"

    logger.info(f"Software export generated by {current_user.username}: {len(data)} items")
    return generate_csv(data, filename)


# ==================== IP ADDRESSES EXPORT ====================

@router.get("/ip-addresses")
def export_ip_addresses(
    subnet_id: Optional[int] = None,
    status: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_admin_user)
):
    """Export IP addresses to CSV."""
    query = db.query(models.IPAddress).options(
        joinedload(models.IPAddress.subnet),
        joinedload(models.IPAddress.equipment)
    )

    # Apply entity filter via subnet
    if current_user.entity_id:
        query = query.join(models.Subnet).filter(
            models.Subnet.entity_id == current_user.entity_id
        )

    # Apply filters
    if subnet_id:
        query = query.filter(models.IPAddress.subnet_id == subnet_id)
    if status:
        query = query.filter(models.IPAddress.status == status)

    ip_addresses = query.order_by(models.IPAddress.address).all()

    data = []
    for ip in ip_addresses:
        data.append({
            "address": ip.address,
            "subnet": ip.subnet.cidr if ip.subnet else "",
            "status": ip.status,
            "hostname": ip.hostname or "",
            "mac_address": ip.mac_address or "",
            "equipment": ip.equipment.name if ip.equipment else "",
            "description": ip.description or "",
            "last_seen": ip.last_seen.isoformat() if ip.last_seen else "",
            "created_at": ip.created_at.isoformat() if ip.created_at else ""
        })

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"ip_addresses_export_{timestamp}.csv"

    logger.info(f"IP addresses export generated by {current_user.username}: {len(data)} items")
    return generate_csv(data, filename)


# ==================== AUDIT LOGS EXPORT ====================

@router.get("/audit-logs")
def export_audit_logs(
    action: Optional[str] = None,
    resource_type: Optional[str] = None,
    username: Optional[str] = None,
    date_from: Optional[str] = None,
    date_to: Optional[str] = None,
    limit: int = Query(default=1000, le=10000),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_admin_user)
):
    """Export audit logs to CSV (admin only)."""
    query = db.query(models.AuditLog)

    # Apply filters
    if action:
        query = query.filter(models.AuditLog.action == action)
    if resource_type:
        query = query.filter(models.AuditLog.resource_type == resource_type)
    if username:
        query = query.filter(models.AuditLog.username.ilike(f"%{username}%"))
    if date_from:
        try:
            from_date = datetime.fromisoformat(date_from)
            query = query.filter(models.AuditLog.timestamp >= from_date)
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid date_from format. Use ISO format.")
    if date_to:
        try:
            to_date = datetime.fromisoformat(date_to)
            query = query.filter(models.AuditLog.timestamp <= to_date)
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid date_to format. Use ISO format.")

    logs = query.order_by(models.AuditLog.timestamp.desc()).limit(limit).all()

    data = []
    for log in logs:
        data.append({
            "timestamp": log.timestamp.isoformat() if log.timestamp else "",
            "username": log.username or "",
            "action": log.action,
            "resource_type": log.resource_type or "",
            "resource_id": log.resource_id or "",
            "ip_address": log.ip_address or "",
            "extra_data": str(log.extra_data) if log.extra_data else ""
        })

    timestamp_str = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"audit_logs_export_{timestamp_str}.csv"

    logger.info(f"Audit logs export generated by {current_user.username}: {len(data)} items")
    return generate_csv(data, filename)
