"""Add DCIM, contracts, software, network ports, attachments and entities

Revision ID: 1ae77e47ec5a
Revises: 
Create Date: 2025-12-24 05:23:50.930366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae77e47ec5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('equipment', sa.Column('warranty_months', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('end_of_support', sa.DateTime(), nullable=True))
    op.add_column('equipment', sa.Column('rack_id', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('position_u', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('height_u', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('power_consumption_watts', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('pdu_id', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('pdu_port', sa.String(), nullable=True))
    op.add_column('equipment', sa.Column('redundant_pdu_id', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('redundant_pdu_port', sa.String(), nullable=True))
    op.add_column('equipment', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equipment', 'entities', ['entity_id'], ['id'])
    op.create_foreign_key(None, 'equipment', 'pdus', ['pdu_id'], ['id'])
    op.create_foreign_key(None, 'equipment', 'pdus', ['redundant_pdu_id'], ['id'])
    op.create_foreign_key(None, 'equipment', 'racks', ['rack_id'], ['id'])
    op.add_column('locations', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'locations', 'entities', ['entity_id'], ['id'])
    op.add_column('subnets', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subnets', 'entities', ['entity_id'], ['id'])
    op.add_column('users', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'entities', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'entity_id')
    op.drop_constraint(None, 'subnets', type_='foreignkey')
    op.drop_column('subnets', 'entity_id')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'entity_id')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'entity_id')
    op.drop_column('equipment', 'redundant_pdu_port')
    op.drop_column('equipment', 'redundant_pdu_id')
    op.drop_column('equipment', 'pdu_port')
    op.drop_column('equipment', 'pdu_id')
    op.drop_column('equipment', 'power_consumption_watts')
    op.drop_column('equipment', 'height_u')
    op.drop_column('equipment', 'position_u')
    op.drop_column('equipment', 'rack_id')
    op.drop_column('equipment', 'end_of_support')
    op.drop_column('equipment', 'warranty_months')
    op.drop_column('equipment', 'purchase_price')
    # ### end Alembic commands ###
