"""add_hierarchy_level_to_equipment_types

Revision ID: 6dd20f20f76e
Revises: 20251225_refresh_tokens
Create Date: 2026-01-06 04:58:18.496653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd20f20f76e'
down_revision: Union[str, None] = '20251225_refresh_tokens'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_types', sa.Column('hierarchy_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_types', 'hierarchy_level')
    # ### end Alembic commands ###
